version: 2
#
# CircleCI Config for eMasters Connection API
# Full CI/CD Workflow
# Can extend later if needed
jobs:
    # The build job
    build:
        working_directory: ~/app
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - run:
                 name: building dependencies
                 command: npm install
            - run:
                 name: Generate Dockerfile
                 command: |
                 cat > Dockerfile <<EOF

                 FROM node:10-alpine
                 RUN mkdir -p ~/eMasters-connection-api
                 WORKDIR ~/eMasters-connection-api
                 COPY . .
                 RUN npm install
                 EXPOSE 80
                 CMD [ "node", "index.js" ]
                 EOF
            - run:
                 name: build image
                 command: more Dockerfile 
                 #command: ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-191-199-62.us-east-2.compute.amazonaws.com "cd ~/proak-dota2; sh deploy.sh"
     # The build job
     deploy:
            - run:
                 name: Deploying to EC2
                 # All deployement steps are in one file included
                 # deploy.sh will fetch code, run docker, and launch app.
                 command: ls
                 #command: ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-191-199-62.us-east-2.compute.amazonaws.com "cd ~/proak-dota2; sh deploy.sh"
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy
